include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style rules
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
    
    # Error prevention
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    avoid_type_to_string: true
    
    # Best practices
    prefer_final_locals: true
    prefer_final_fields: true
    avoid_relative_lib_imports: true
    use_key_in_widget_constructors: true
    
    # Performance
    avoid_unnecessary_containers: true
    prefer_contains: true